# Usar la última imagen de Ubuntu
FROM ubuntu:latest

# Actualizar e instalar actualizaciones del sistema
RUN apt-get update && apt-get upgrade -y

# Comando por defecto al correr el contenedor
CMD echo "Hello, World!"
